# Generated by Django 5.2.1 on 2025-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(default=0),
        ),
    ]
